# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{active_scaffold_export}
  s.version = "0.9.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Chris Shoemaker"]
  s.date = %q{2010-11-16}
  s.description = %q{This Active Scaffold plugin provides a configurable CSV 'Export' action for Active Scaffold controllers}
  s.email = %q{chris@mojotech.com}
  s.extra_rdoc_files = [
    "README.markdown"
  ]
  s.files = [
    "MIT-LICENSE",
     "README.markdown",
     "Rakefile",
     "VERSION",
     "active_scaffold_export.gemspec",
     "frontends/default/images/export.png",
     "frontends/default/stylesheets/export-stylesheet-ie.css",
     "frontends/default/stylesheets/export-stylesheet.css",
     "frontends/default/views/_export_form_body.html.erb",
     "frontends/default/views/_show_export.html.erb",
     "frontends/default/views/show_export.html.erb",
     "init.rb",
     "install.rb",
     "lib/active_scaffold/actions/export.rb",
     "lib/active_scaffold/config/export.rb",
     "lib/active_scaffold/helpers/export_helpers.rb",
     "lib/active_scaffold/helpers/view_helpers_override.rb",
     "lib/active_scaffold_export/config/core.rb"
  ]
  s.homepage = %q{http://github.com/mojotech/active_scaffold_export}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Active Scaffold plugin for CSV exports}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<fastercsv>, [">= 0"])
    else
      s.add_dependency(%q<fastercsv>, [">= 0"])
    end
  else
    s.add_dependency(%q<fastercsv>, [">= 0"])
  end
end

